In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('US_daily.csv')
print(df.columns.tolist())

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Company', 'mv100', 'mv50', 'mv9', 'bb_bbm', 'bb_bbh', 'bb_bbl', 'rsi14', 'rsimv9', 'rsi50', 'wd', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'MF Multiplier', 'MF Volume', 'f34', 'f35', 'feature_0', 'feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19', 'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29', 'feature_30', 'feature_31', 'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36', 'feature_37', 'feature_38', 'feature_39', 'feature_40', 'feature_41', 'feature_42', 'feature_43', 'feature_44', 'feature_45', 'feature_46', 'feature_47', 'feature_48', 'feature_49', 'feature_50', 'feature_51', 'feature_52', 'feature_53', 'feature_54', 'feature_55', 'feature_56', 'feature_57', 'feature_58', 'feature_59', 'feature_60', 'feature_61', 'feature_62', 'feature_63', 'feature_64', 'feature_65', 'feature_66', 'feature_67', 'feature_68', 'feature_69', 'feature_70', 'feature_71', 'feature_72', 'feature_73', 'feature_74', 'feature_75', 'feature_76', 'feature_77', 'feature_78', 'feature_79', 'feature_80', 'feature_81', 'feature_82', 'feature_83', 'feature_84', 'feature_85', 'feature_86', 'feature_87', 'feature_88', 'feature_89', 'feature_90', 'feature_91', 'feature_92', 'feature_93', 'feature_94', 'feature_95', 'feature_96', 'feature_97', 'feature_98', 'feature_99', 'Next_Day_Close']

In [3]:
df

,Date,Open,High,Low,Close,Volume,Company,mv100,mv50,mv9,...,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,Next_Day_Close
0,2020-05-26,82.248296,86.330164,82.000375,84.842628,41233900,JPM,96.673945,80.039495,79.036118,...,0.000015,0.000022,0.000018,0.000012,0.000008,0.000018,0.000021,0.000010,0.000012,89.756813
1,2020-05-26,102.962943,104.563268,102.696227,102.891823,4822000,TXN,102.827698,96.067687,100.253275,...,0.000024,0.000035,0.000028,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019,104.749977
2,2020-05-26,278.731152,279.229389,274.970867,277.217651,4567800,UNH,259.624948,251.507018,271.754730,...,0.000007,0.000010,0.000008,0.000005,0.000003,0.000008,0.000010,0.000004,0.000005,285.565430
3,2020-05-26,43.217167,43.492685,42.650383,42.744846,20830500,VZ,44.422925,43.453458,42.963517,...,0.000027,0.000040,0.000032,0.000022,0.000015,0.000031,0.000039,0.000018,0.000021,43.406097
4,2020-05-26,56.814993,57.529449,56.775299,57.259541,5627800,PM,61.842569,56.759710,55.113540,...,0.000035,0.000051,0.000041,0.000027,0.000019,0.000039,0.000050,0.000023,0.000028,58.672588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34423,2023-12-28,104.964769,105.558851,104.539008,105.202400,5689100,ORCL,110.172590,108.298763,104.422386,...,0.000008,0.000012,0.000009,0.000006,0.000004,0.000009,0.000011,0.000005,0.000006,104.390480
34424,2023-12-28,106.412482,108.586193,106.015456,108.010506,9352900,NKE,103.250478,108.674890,114.839322,...,0.000033,0.000048,0.000039,0.000026,0.000018,0.000037,0.000047,0.000022,0.000027,107.762367
34425,2023-12-28,49.359866,49.408659,49.203722,49.262276,8549900,CSCO,51.231929,49.245492,48.910962,...,0.000015,0.000022,0.000018,0.000012,0.000008,0.000017,0.000021,0.000010,0.000011,49.301311
34426,2023-12-28,662.863459,663.868939,658.622617,660.125793,1496900,COST,561.175412,582.071428,654.362352,...,0.000033,0.000047,0.000039,0.000026,0.000018,0.000038,0.000047,0.000022,0.000026,657.119385
34427,2023-12-28,144.847624,145.551159,144.401728,144.530548,4928800,QCOM,117.247060,124.975209,142.183261,...,0.000026,0.000037,0.000031,0.000021,0.000014,0.000029,0.000037,0.000017,0.000020,143.311783

In [4]:
train_df = df[df['Date'] < '2023-04-01']
validation_df = df[(df['Date'] >= '2023-04-01') & (df['Date'] < '2023-08-01')]
test_df = df[df['Date'] >= '2023-08-01']

# 2020.5.26-2023.4.1 Train
# 2023.4.1-2023.8.1 Val
# 2023.8.1-2023.12.28 Test

print(f"Training set size: {len(train_df)}")
print(f"Validation set size: {len(validation_df)}")
print(f"Testing set size: {len(test_df)}")

Training set size: 27322
Validation set size: 3116
Testing set size: 3990

## Model_2 OHLC+Indicators+Descriptions

In [5]:
train_df

,Date,Open,High,Low,Close,Volume,Company,mv100,mv50,mv9,...,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99,Next_Day_Close
0,2020-05-26,82.248296,86.330164,82.000375,84.842628,41233900,JPM,96.673945,80.039495,79.036118,...,0.000015,0.000022,0.000018,0.000012,0.000008,0.000018,0.000021,0.000010,0.000012,89.756813
1,2020-05-26,102.962943,104.563268,102.696227,102.891823,4822000,TXN,102.827698,96.067687,100.253275,...,0.000024,0.000035,0.000028,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019,104.749977
2,2020-05-26,278.731152,279.229389,274.970867,277.217651,4567800,UNH,259.624948,251.507018,271.754730,...,0.000007,0.000010,0.000008,0.000005,0.000003,0.000008,0.000010,0.000004,0.000005,285.565430
3,2020-05-26,43.217167,43.492685,42.650383,42.744846,20830500,VZ,44.422925,43.453458,42.963517,...,0.000027,0.000040,0.000032,0.000022,0.000015,0.000031,0.000039,0.000018,0.000021,43.406097
4,2020-05-26,56.814993,57.529449,56.775299,57.259541,5627800,PM,61.842569,56.759710,55.113540,...,0.000035,0.000051,0.000041,0.000027,0.000019,0.000039,0.000050,0.000023,0.000028,58.672588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27317,2023-03-31,81.918716,82.928543,81.324140,82.862480,6142400,MS,85.962422,88.708458,81.349309,...,0.000008,0.000013,0.000010,0.000007,0.000004,0.000010,0.000013,0.000006,0.000007,82.258476
27318,2023-03-31,344.755048,349.930762,344.440169,349.743805,1513500,LIN,327.096621,331.536114,340.860687,...,0.000014,0.000021,0.000017,0.000011,0.000008,0.000017,0.000021,0.000009,0.000011,352.361115
27319,2023-03-31,175.538948,175.856955,174.729483,175.673859,4479800,PEP,170.009203,167.385168,172.598726,...,0.000034,0.000048,0.000039,0.000026,0.000019,0.000038,0.000049,0.000023,0.000027,175.866577
27320,2023-03-31,149.488826,150.564503,148.828334,150.375778,4957300,ABBV,145.863364,143.188283,148.332445,...,0.000028,0.000040,0.000032,0.000022,0.000015,0.000031,0.000040,0.000019,0.000022,151.366516
27321,2023-03-31,382.290009,385.730011,380.260010,385.369995,3063400,ADBE,346.735200,359.111400,374.763329,...,0.000014,0.000021,0.000017,0.000011,0.000008,0.000016,0.000020,0.000009,0.000011,380.079987

In [6]:
columns_to_drop = ['Date', 'Company','Next_Day_Close']

train_df_reduced = train_df.drop(columns=columns_to_drop)
train_data = train_df_reduced.iloc[:, :52].to_numpy() 
train_vector = train_df_reduced.iloc[:, 52:].to_numpy()
train_label = train_df['Next_Day_Close'].to_numpy()


validation_df_reduced = validation_df.drop(columns=columns_to_drop)
val_data = validation_df_reduced.iloc[:, :52].to_numpy() 
val_vector = validation_df_reduced.iloc[:, 52:].to_numpy()
val_label = validation_df['Next_Day_Close'].to_numpy()


test_df_reduced = test_df.drop(columns=columns_to_drop)
test_data = test_df_reduced.iloc[:, :52].to_numpy() 
test_vector = test_df_reduced.iloc[:, 52:].to_numpy()
Test_label = test_df['Next_Day_Close'].to_numpy()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_data = scaler.fit_transform(train_data)
val_data = scaler.transform(val_data)
test_data = scaler.transform(test_data)

train_data = train_data.reshape(-1, 1, 52)
val_data = val_data.reshape(-1, 1, 52)
test_data = test_data.reshape(-1, 1, 52)

print("Train data shape:", train_data.shape)
print("Train vector shape:", train_vector.shape)
print("Train label shape:", train_label.shape)

print("Val data shape:", val_data.shape)
print("Val vector shape:", val_vector.shape)
print("Val label shape:", val_label.shape)

print("Test data shape:", test_data.shape)
print("Test vector shape:", test_vector.shape)
print("Test label shape:", Test_label.shape)

Train data shape: (27322, 1, 52)
Train vector shape: (27322, 100)
Train label shape: (27322,)
Val data shape: (3116, 1, 52)
Val vector shape: (3116, 100)
Val label shape: (3116,)
Test data shape: (3990, 1, 52)
Test vector shape: (3990, 100)
Test label shape: (3990,)

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Dropout, GlobalAveragePooling1D, Bidirectional, LSTM, LayerNormalization, Concatenate, Attention, BatchNormalization, Reshape
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

INPUT_DIMS = 52
TIME_STEPS = 1
d_model = 256

def AdvancedModel():
    data_input = Input(shape=(TIME_STEPS, INPUT_DIMS))
    x1 = Bidirectional(LSTM(d_model // 2, return_sequences=False))(data_input)
    x1 = BatchNormalization()(x1)
    x1 = Dense(128, activation='relu')(x1)

    vector_input = Input(shape=(100,))

    concatenated = Concatenate()([x1, vector_input])

    x = Dense(256, activation='relu')(concatenated)
    x = BatchNormalization()(x)
    x = Dense(128, activation='relu')(x)
    x = BatchNormalization()(x)
    x = Dense(20, activation='relu')(x)
    x = BatchNormalization()(x)

    outputs = Dense(1)(x)

    model = Model(inputs=[data_input, vector_input], outputs=outputs)
    return model

model = AdvancedModel()

adam_optimizer = tf.keras.optimizers.legacy.Adam(learning_rate=0.001)
model.compile(optimizer=adam_optimizer, loss='mean_squared_error', metrics=['mean_absolute_error'])

model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_3 (InputLayer)        [(None, 1, 52)]              0         []

 bidirectional_1 (Bidirecti  (None, 256)                  185344    ['input_3[0][0]']
 onal)

 batch_normalization_4 (Bat  (None, 256)                  1024      ['bidirectional_1[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 128)                  32896     ['batch_normalization_4[0][0]'
                                                                    ]

 input_4 (InputLayer)        [(None, 100)]                0         []

 concatenate_1 (Concatenate  (None, 228)                  0         ['dense_5[0][0]',
 )                                                                   'input_4[0][0]']

 dense_6 (Dense)             (None, 256)                  58624     ['concatenate_1[0][0]']

 batch_normalization_5 (Bat  (None, 256)                  1024      ['dense_6[0][0]']
 chNormalization)

 dense_7 (Dense)             (None, 128)                  32896     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 128)                  512       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 20)                   2580      ['batch_normalization_6[0][0]'
                                                                    ]

 batch_normalization_7 (Bat  (None, 20)                   80        ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 1)                    21        ['batch_normalization_7[0][0]'
                                                                    ]

==================================================================================================
Total params: 315001 (1.20 MB)
Trainable params: 313681 (1.20 MB)
Non-trainable params: 1320 (5.16 KB)
__________________________________________________________________________________________________

In [10]:
from tensorflow.keras.callbacks import EarlyStopping


early_stopping = EarlyStopping(
    monitor='val_loss',  # Metric to monitor, e.g., validation loss
    patience=3,  # Number of epochs with no improvement after which training will be stopped
    verbose=0,  # Verbosity mode
    restore_best_weights=True  # Restore model weights from the epoch with the best value of the monitored quantity
    )

# Train the model
history = model.fit(
    [train_data, train_vector], train_label,
    validation_data=([val_data, val_vector], val_label),
    epochs=50,  # Adjust the number of epochs as needed
    batch_size=32, 
    callbacks=[early_stopping]# Adjust the batch size as needed
)

Epoch 1/50
854/854 [==============================] - 4s 3ms/step - loss: 42927.0703 - mean_absolute_error: 171.7540 - val_loss: 32303.1484 - val_mean_absolute_error: 165.0957
Epoch 2/50
854/854 [==============================] - 2s 3ms/step - loss: 18760.9004 - mean_absolute_error: 121.8456 - val_loss: 8863.3770 - val_mean_absolute_error: 92.2832
Epoch 3/50
854/854 [==============================] - 2s 3ms/step - loss: 4985.0693 - mean_absolute_error: 61.5391 - val_loss: 867.3870 - val_mean_absolute_error: 28.1730
Epoch 4/50
854/854 [==============================] - 2s 3ms/step - loss: 1203.6161 - mean_absolute_error: 27.1207 - val_loss: 146.4395 - val_mean_absolute_error: 8.3495
Epoch 5/50
854/854 [==============================] - 2s 3ms/step - loss: 779.6556 - mean_absolute_error: 21.7478 - val_loss: 178.8669 - val_mean_absolute_error: 10.2981
Epoch 6/50
854/854 [==============================] - 2s 3ms/step - loss: 765.4606 - mean_absolute_error: 21.6806 - val_loss: 335.6931 - val_mean_absolute_error: 14.9035

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 6))

plt.subplot(1, 2, 1) 
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(loc='upper right')

plt.subplot(1, 2, 2) 
plt.plot(history.history['mean_absolute_error'], label='Train MAE')
plt.plot(history.history['val_mean_absolute_error'], label='Validation MAE')
plt.title('Model MAE')
plt.ylabel('Mean Absolute Error')
plt.xlabel('Epoch')
plt.legend(loc='upper right')

plt.show()

In [11]:
# Evaluate the model on the test set
test_loss, test_mae = model.evaluate([test_data, test_vector], Test_label)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

125/125 [==============================] - 0s 691us/step - loss: 183.2697 - mean_absolute_error: 8.9717
Test Loss: 183.26966857910156, Test MAE: 8.971657752990723

In [ ]:
predictions = model.predict([test_data, test_vector])[:30]

true_values = Test_label[:30]

plt.figure(figsize=(10, 6))
plt.plot(true_values, label='True Values', marker='o')
plt.plot(predictions, label='Predictions', marker='x')
plt.title('Comparison of Actual and Predicted Values')
plt.xlabel('Sample Index')
plt.ylabel('Next Day Close Price')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
predictions = model.predict([test_data, test_vector])

In [ ]:
import pandas as pd
predictions = predictions.reshape(3990)
company = test_df['Company']

data = {
    'Company': company,  
    'True Labels': Test_label,
    'Predictions': predictions
}

df_eval = pd.DataFrame(data)
df_eval

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# Function to calculate RMSE
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# Group by company and calculate each metric
grouped = df_eval.groupby('Company').apply(lambda x: pd.Series({
    'MAE': mean_absolute_error(x['True Labels'], x['Predictions']),
    'RMSE': rmse(x['True Labels'], x['Predictions']),
    'Count': len(x)
}))

ranked_by_mae = grouped.sort_values('MAE', ascending=True)

ranked_by_mae

In [ ]:
import matplotlib.pyplot as plt

plot_data = df_eval[df_eval['Company'] == 'WFC']

plt.figure(figsize=(10, 6))
plt.plot(plot_data['True Labels'], label='True Values', marker='o')
plt.plot(plot_data['Predictions'], label='Predictions', marker='x')
plt.title('Comparison of Actual and Predicted Values for WFC')
plt.xlabel('Sample Index')
plt.ylabel('Next Day Close Price')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plot_data = df_eval[df_eval['Company'] == 'LLY']

plt.figure(figsize=(10, 6))
plt.plot(plot_data['True Labels'], label='True Values', marker='o')
plt.plot(plot_data['Predictions'], label='Predictions', marker='x')
plt.title('Comparison of Actual and Predicted Values for LLY')
plt.xlabel('Sample Index')
plt.ylabel('Next Day Close Price')
plt.legend()
plt.grid(True)
plt.show()

In [12]:
result_MAE = []
result_MSE = []
for i in range(20):
    model = AdvancedModel()
    adam_optimizer = tf.keras.optimizers.legacy.Adam(learning_rate=0.001)
    model.compile(optimizer=adam_optimizer, loss='mean_squared_error', metrics=['mean_absolute_error'])
    early_stopping = EarlyStopping(
        monitor='val_loss',  # Metric to monitor, e.g., validation loss
        patience=2,  # Number of epochs with no improvement after which training will be stopped
        verbose=0,  # Verbosity mode
        restore_best_weights=True  # Restore model weights from the epoch with the best value of the monitored quantity
        )
    model.fit(
        [train_data, train_vector], train_label,
        validation_data=([val_data, val_vector], val_label),
        epochs=50,  
        batch_size=32,  
        verbose=0,
        callbacks=[early_stopping]
    )
    test_loss, test_mae = model.evaluate([test_data, test_vector], Test_label)
    result_MAE.append(test_mae)
    result_MSE.append(test_loss)
print('MAE : ',np.mean(result_MAE))
print('MSE : ',np.mean(result_MSE))

125/125 [==============================] - 0s 882us/step - loss: 129.1663 - mean_absolute_error: 5.9167
125/125 [==============================] - 0s 829us/step - loss: 54.0147 - mean_absolute_error: 5.0937
125/125 [==============================] - 0s 833us/step - loss: 52.3064 - mean_absolute_error: 4.6240
125/125 [==============================] - 0s 850us/step - loss: 72.4617 - mean_absolute_error: 5.1057
125/125 [==============================] - 0s 981us/step - loss: 60.5693 - mean_absolute_error: 4.7560
125/125 [==============================] - 0s 914us/step - loss: 95.5514 - mean_absolute_error: 6.8922
125/125 [==============================] - 0s 826us/step - loss: 77.8508 - mean_absolute_error: 5.6296
125/125 [==============================] - 0s 921us/step - loss: 55.7614 - mean_absolute_error: 5.1091
125/125 [==============================] - 0s 844us/step - loss: 56.7181 - mean_absolute_error: 5.1883
125/125 [==============================] - 0s 741us/step - loss: 52.2075 - mean_absolute_error: 4.8314
125/125 [==============================] - 0s 944us/step - loss: 49.2820 - mean_absolute_error: 4.8495
125/125 [==============================] - 0s 742us/step - loss: 49.2470 - mean_absolute_error: 5.0061
125/125 [==============================] - 0s 755us/step - loss: 72.4868 - mean_absolute_error: 5.8644
125/125 [==============================] - 0s 764us/step - loss: 45.5793 - mean_absolute_error: 4.7281
125/125 [==============================] - 0s 775us/step - loss: 69.6623 - mean_absolute_error: 6.0589
125/125 [==============================] - 0s 798us/step - loss: 77.7040 - mean_absolute_error: 6.5611
125/125 [==============================] - 0s 921us/step - loss: 44.3068 - mean_absolute_error: 4.3678
125/125 [==============================] - 0s 985us/step - loss: 55.9452 - mean_absolute_error: 4.5407
125/125 [==============================] - 0s 926us/step - loss: 95.4112 - mean_absolute_error: 6.9023
125/125 [==============================] - 0s 796us/step - loss: 57.1169 - mean_absolute_error: 4.2790

NameError: name 'np' is not defined

In [13]:
import numpy as np

In [14]:
print('MAE : ',np.mean(result_MAE))
print('MSE : ',np.mean(result_MSE))

MAE :  5.31523551940918
MSE :  66.16746006011962