In [32]:
import yfinance as yf
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime
from pandas_datareader.oecd import OECDReader
from yahooquery import Ticker

start_date = datetime(2020, 1, 1)
end_date = datetime(2023, 12, 31)

companies = ["IBM","AAPL","JPM"]

In [33]:
all_data = pd.DataFrame()

for company in companies:
    tick = yf.Ticker(company)
    data = tick.history(start=start_date, end=end_date)
    data['Company'] = company
    all_data = pd.concat([all_data, data])
    all_data = all_data.sort_values(by='Date', ascending=True)

In [34]:
all_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company
Date,,,,,,,,
2020-01-02 00:00:00-05:00,103.987339,104.695998,103.810180,104.310860,3293436,0.0,0.0,IBM
2020-01-02 00:00:00-05:00,71.962075,73.021202,71.707013,72.960472,135480400,0.0,0.0,AAPL
2020-01-02 00:00:00-05:00,121.720893,122.861575,121.259402,122.852859,10803700,0.0,0.0,JPM
2020-01-03 00:00:00-05:00,102.885847,103.879509,102.878145,103.478966,2482890,0.0,0.0,IBM
2020-01-03 00:00:00-05:00,72.183120,73.016327,72.025225,72.251137,146322800,0.0,0.0,AAPL
...,...,...,...,...,...,...,...,...
2023-12-28 00:00:00-05:00,166.413947,167.701232,166.070009,167.347473,6320100,0.0,0.0,JPM
2023-12-28 00:00:00-05:00,193.629953,194.148591,192.662500,193.071426,34049900,0.0,0.0,AAPL
2023-12-29 00:00:00-05:00,160.675597,161.097516,159.772872,160.479355,2525600,0.0,0.0,IBM
2023-12-29 00:00:00-05:00,193.390581,193.889267,191.226284,192.024185,42628800,0.0,0.0,AAPL
2023-12-29 00:00:00-05:00,167.052652,167.730692,166.689072,167.150925,6431800,0.0,0.0,JPM

In [35]:
print('Shape of balance sheet for companies')
for company in companies:
    ticker = Ticker(company)
    
    balance_sheet = ticker.balance_sheet(frequency='annual')
    balance_sheet['asOfDate'] = pd.to_datetime(balance_sheet['asOfDate'])
    balance_sheet = balance_sheet[(balance_sheet['asOfDate'] >= '2020-01-01') & (balance_sheet['asOfDate'] <= '2023-12-31')]
    balance_sheet = balance_sheet.sort_values(by='asOfDate')
    balance_sheet = balance_sheet.dropna(axis=1)
    
    print(company, balance_sheet.shape)
    print(balance_sheet.columns.tolist())
    
print('Shape of cashflow for companies')
for company in companies:
    ticker = Ticker(company)
    
    cashflow = ticker.cash_flow(frequency='annual')
    cashflow['asOfDate'] = pd.to_datetime(cashflow['asOfDate'])
    cashflow = cashflow[(cashflow['asOfDate'] >= '2020-01-01') & (cashflow['asOfDate'] <= '2023-12-31')]
    cashflow = cashflow.sort_values(by='asOfDate')
    cashflow = cashflow.dropna(axis=1)

    print(company, cashflow.shape)
    print(cashflow.columns.tolist())

print('Shape of income statement for companies')
for company in companies:
    ticker = Ticker(company)
    
    income_statement = ticker.income_statement(frequency='annual')
    income_statement['asOfDate'] = pd.to_datetime(income_statement['asOfDate'])
    income_statement = income_statement[(income_statement['asOfDate'] >= '2020-01-01') & (income_statement['asOfDate'] <= '2023-12-31')]
    income_statement = income_statement.sort_values(by='asOfDate')
    income_statement = income_statement.dropna(axis=1)
    
    print(company, income_statement.shape)
    print(income_statement.columns.tolist())

Shape of balance sheet for companies
IBM (4, 87)
['asOfDate', 'periodType', 'currencyCode', 'AccountsPayable', 'AccountsReceivable', 'AccumulatedDepreciation', 'AllowanceForDoubtfulAccountsReceivable', 'AssetsHeldForSaleCurrent', 'BuildingsAndImprovements', 'CapitalLeaseObligations', 'CapitalStock', 'CashAndCashEquivalents', 'CashCashEquivalentsAndShortTermInvestments', 'CommonStock', 'CommonStockEquity', 'CurrentAccruedExpenses', 'CurrentAssets', 'CurrentCapitalLeaseObligation', 'CurrentDebt', 'CurrentDebtAndCapitalLeaseObligation', 'CurrentDeferredAssets', 'CurrentDeferredLiabilities', 'CurrentDeferredRevenue', 'CurrentLiabilities', 'DefinedPensionBenefit', 'DerivativeProductLiabilities', 'EmployeeBenefits', 'FinishedGoods', 'GainsLossesNotAffectingRetainedEarnings', 'Goodwill', 'GoodwillAndOtherIntangibleAssets', 'GrossAccountsReceivable', 'GrossPPE', 'Inventory', 'InvestedCapital', 'LandAndImprovements', 'LongTermCapitalLeaseObligation', 'LongTermDebt', 'LongTermDebtAndCapitalLeaseObligation', 'LongTermProvisions', 'MachineryFurnitureEquipment', 'MinorityInterest', 'NetDebt', 'NetPPE', 'NetTangibleAssets', 'NonCurrentAccountsReceivable', 'NonCurrentAccruedExpenses', 'NonCurrentDeferredAssets', 'NonCurrentDeferredLiabilities', 'NonCurrentDeferredRevenue', 'NonCurrentDeferredTaxesAssets', 'NonCurrentDeferredTaxesLiabilities', 'NonCurrentPensionAndOtherPostretirementBenefitPlans', 'NonCurrentPrepaidAssets', 'OrdinarySharesNumber', 'OtherCurrentAssets', 'OtherCurrentBorrowings', 'OtherCurrentLiabilities', 'OtherEquityAdjustments', 'OtherIntangibleAssets', 'OtherNonCurrentAssets', 'OtherNonCurrentLiabilities', 'OtherProperties', 'OtherReceivables', 'OtherShortTermInvestments', 'Payables', 'PayablesAndAccruedExpenses', 'PensionandOtherPostRetirementBenefitPlansCurrent', 'Properties', 'Receivables', 'RestrictedCash', 'RetainedEarnings', 'ShareIssued', 'StockholdersEquity', 'TangibleBookValue', 'TotalAssets', 'TotalCapitalization', 'TotalDebt', 'TotalEquityGrossMinorityInterest', 'TotalLiabilitiesNetMinorityInterest', 'TotalNonCurrentAssets', 'TotalNonCurrentLiabilitiesNetMinorityInterest', 'TotalTaxPayable', 'TreasurySharesNumber', 'TreasuryStock', 'WorkInProcess', 'WorkingCapital']
AAPL (4, 65)
['asOfDate', 'periodType', 'currencyCode', 'AccountsPayable', 'AccountsReceivable', 'AccumulatedDepreciation', 'AvailableForSaleSecurities', 'CapitalLeaseObligations', 'CapitalStock', 'CashAndCashEquivalents', 'CashCashEquivalentsAndShortTermInvestments', 'CashEquivalents', 'CashFinancial', 'CommercialPaper', 'CommonStock', 'CommonStockEquity', 'CurrentAssets', 'CurrentCapitalLeaseObligation', 'CurrentDebt', 'CurrentDebtAndCapitalLeaseObligation', 'CurrentDeferredLiabilities', 'CurrentDeferredRevenue', 'CurrentLiabilities', 'GainsLossesNotAffectingRetainedEarnings', 'GrossPPE', 'Inventory', 'InvestedCapital', 'InvestmentinFinancialAssets', 'InvestmentsAndAdvances', 'LandAndImprovements', 'Leases', 'LongTermCapitalLeaseObligation', 'LongTermDebt', 'LongTermDebtAndCapitalLeaseObligation', 'MachineryFurnitureEquipment', 'NetDebt', 'NetPPE', 'NetTangibleAssets', 'OrdinarySharesNumber', 'OtherCurrentAssets', 'OtherCurrentBorrowings', 'OtherCurrentLiabilities', 'OtherEquityAdjustments', 'OtherNonCurrentAssets', 'OtherNonCurrentLiabilities', 'OtherProperties', 'OtherReceivables', 'OtherShortTermInvestments', 'Payables', 'PayablesAndAccruedExpenses', 'Properties', 'Receivables', 'RetainedEarnings', 'ShareIssued', 'StockholdersEquity', 'TangibleBookValue', 'TotalAssets', 'TotalCapitalization', 'TotalDebt', 'TotalEquityGrossMinorityInterest', 'TotalLiabilitiesNetMinorityInterest', 'TotalNonCurrentAssets', 'TotalNonCurrentLiabilitiesNetMinorityInterest', 'TradeandOtherPayablesNonCurrent', 'WorkingCapital']
JPM (4, 47)
['asOfDate', 'periodType', 'currencyCode', 'AccountsPayable', 'AccountsReceivable', 'AdditionalPaidInCapital', 'CapitalStock', 'CashAndCashEquivalents', 'CashFinancial', 'CommonStock', 'CommonStockEquity', 'CurrentDebt', 'CurrentDebtAndCapitalLeaseObligation', 'GainsLossesNotAffectingRetainedEarnings', 'Goodwill', 'GoodwillAndOtherIntangibleAssets', 'HeldToMaturitySecurities', 'InvestedCapital', 'InvestmentsAndAdvances', 'LongTermDebt', 'LongTermDebtAndCapitalLeaseObligation', 'NetPPE', 'NetTangibleAssets', 'OrdinarySharesNumber', 'OtherCurrentBorrowings', 'OtherEquityAdjustments', 'OtherIntangibleAssets', 'OtherPayable', 'OtherShortTermInvestments', 'Payables', 'PayablesAndAccruedExpenses', 'PreferredSharesNumber', 'PreferredStock', 'PreferredStockEquity', 'Receivables', 'RetainedEarnings', 'ShareIssued', 'StockholdersEquity', 'TangibleBookValue', 'TotalAssets', 'TotalCapitalization', 'TotalDebt', 'TotalEquityGrossMinorityInterest', 'TotalLiabilitiesNetMinorityInterest', 'TradingSecurities', 'TreasurySharesNumber', 'TreasuryStock']
Shape of cashflow for companies
IBM (4, 60)
['asOfDate', 'periodType', 'currencyCode', 'AmortizationCashFlow', 'AmortizationOfIntangibles', 'BeginningCashPosition', 'CapitalExpenditure', 'CashDividendsPaid', 'CashFlowFromContinuingFinancingActivities', 'CashFlowFromContinuingInvestingActivities', 'CashFlowFromContinuingOperatingActivities', 'ChangeInAccountPayable', 'ChangeInCashSupplementalAsReported', 'ChangeInInventory', 'ChangeInOtherWorkingCapital', 'ChangeInPayable', 'ChangeInPayablesAndAccruedExpense', 'ChangeInReceivables', 'ChangeInWorkingCapital', 'ChangesInCash', 'CommonStockDividendPaid', 'CommonStockPayments', 'DeferredIncomeTax', 'DeferredTax', 'Depreciation', 'DepreciationAmortizationDepletion', 'DepreciationAndAmortization', 'EffectOfExchangeRateChanges', 'EndCashPosition', 'FinancingCashFlow', 'FreeCashFlow', 'IncomeTaxPaidSupplementalData', 'InterestPaidSupplementalData', 'InvestingCashFlow', 'IssuanceOfDebt', 'LongTermDebtIssuance', 'LongTermDebtPayments', 'NetBusinessPurchaseAndSale', 'NetCommonStockIssuance', 'NetIncome', 'NetIncomeFromContinuingOperations', 'NetIntangiblesPurchaseAndSale', 'NetInvestmentPurchaseAndSale', 'NetIssuancePaymentsOfDebt', 'NetLongTermDebtIssuance', 'NetOtherFinancingCharges', 'NetPPEPurchaseAndSale', 'NetShortTermDebtIssuance', 'OperatingCashFlow', 'OperatingGainsLosses', 'PensionAndEmployeeBenefitExpense', 'PurchaseOfBusiness', 'PurchaseOfIntangibles', 'PurchaseOfInvestment', 'PurchaseOfPPE', 'RepaymentOfDebt', 'RepurchaseOfCapitalStock', 'SaleOfInvestment', 'SaleOfPPE', 'StockBasedCompensation']
AAPL (4, 51)
['asOfDate', 'periodType', 'currencyCode', 'BeginningCashPosition', 'CapitalExpenditure', 'CashDividendsPaid', 'CashFlowFromContinuingFinancingActivities', 'CashFlowFromContinuingInvestingActivities', 'CashFlowFromContinuingOperatingActivities', 'ChangeInAccountPayable', 'ChangeInCashSupplementalAsReported', 'ChangeInInventory', 'ChangeInOtherCurrentAssets', 'ChangeInOtherCurrentLiabilities', 'ChangeInPayable', 'ChangeInPayablesAndAccruedExpense', 'ChangeInReceivables', 'ChangeInWorkingCapital', 'ChangesInAccountReceivables', 'ChangesInCash', 'CommonStockDividendPaid', 'CommonStockPayments', 'DepreciationAmortizationDepletion', 'DepreciationAndAmortization', 'EndCashPosition', 'FinancingCashFlow', 'FreeCashFlow', 'IncomeTaxPaidSupplementalData', 'InterestPaidSupplementalData', 'InvestingCashFlow', 'IssuanceOfDebt', 'LongTermDebtIssuance', 'LongTermDebtPayments', 'NetCommonStockIssuance', 'NetIncome', 'NetIncomeFromContinuingOperations', 'NetInvestmentPurchaseAndSale', 'NetIssuancePaymentsOfDebt', 'NetLongTermDebtIssuance', 'NetOtherFinancingCharges', 'NetOtherInvestingChanges', 'NetPPEPurchaseAndSale', 'NetShortTermDebtIssuance', 'OperatingCashFlow', 'OtherNonCashItems', 'PurchaseOfInvestment', 'PurchaseOfPPE', 'RepaymentOfDebt', 'RepurchaseOfCapitalStock', 'SaleOfInvestment', 'StockBasedCompensation']
JPM (4, 52)
['asOfDate', 'periodType', 'currencyCode', 'BeginningCashPosition', 'CashDividendsPaid', 'CashFlowFromContinuingFinancingActivities', 'CashFlowFromContinuingInvestingActivities', 'CashFlowFromContinuingOperatingActivities', 'ChangeInAccountPayable', 'ChangeInCashSupplementalAsReported', 'ChangeInOtherCurrentAssets', 'ChangeInOtherWorkingCapital', 'ChangeInPayable', 'ChangeInPayablesAndAccruedExpense', 'ChangeInReceivables', 'ChangeInWorkingCapital', 'ChangesInAccountReceivables', 'ChangesInCash', 'CommonStockPayments', 'DeferredIncomeTax', 'DeferredTax', 'DepreciationAmortizationDepletion', 'DepreciationAndAmortization', 'EffectOfExchangeRateChanges', 'EndCashPosition', 'FinancingCashFlow', 'FreeCashFlow', 'IncomeTaxPaidSupplementalData', 'InterestPaidSupplementalData', 'InvestingCashFlow', 'IssuanceOfCapitalStock', 'IssuanceOfDebt', 'LongTermDebtIssuance', 'LongTermDebtPayments', 'NetCommonStockIssuance', 'NetIncome', 'NetIncomeFromContinuingOperations', 'NetInvestmentPurchaseAndSale', 'NetIssuancePaymentsOfDebt', 'NetLongTermDebtIssuance', 'NetOtherFinancingCharges', 'NetOtherInvestingChanges', 'NetPreferredStockIssuance', 'NetShortTermDebtIssuance', 'OperatingCashFlow', 'OtherNonCashItems', 'PreferredStockIssuance', 'PreferredStockPayments', 'PurchaseOfInvestment', 'RepaymentOfDebt', 'RepurchaseOfCapitalStock', 'SaleOfInvestment']
Shape of income statement for companies
IBM (6, 7)
['asOfDate', 'periodType', 'currencyCode', 'BasicAverageShares', 'BasicEPS', 'DilutedAverageShares', 'DilutedEPS']
AAPL (6, 7)
['asOfDate', 'periodType', 'currencyCode', 'BasicAverageShares', 'BasicEPS', 'DilutedAverageShares', 'DilutedEPS']
JPM (6, 7)
['asOfDate', 'periodType', 'currencyCode', 'BasicAverageShares', 'BasicEPS', 'DilutedAverageShares', 'DilutedEPS']

In [36]:
balance_sheet

,asOfDate,periodType,currencyCode,AccountsPayable,AccountsReceivable,AdditionalPaidInCapital,CapitalStock,CashAndCashEquivalents,CashFinancial,CommonStock,...,StockholdersEquity,TangibleBookValue,TotalAssets,TotalCapitalization,TotalDebt,TotalEquityGrossMinorityInterest,TotalLiabilitiesNetMinorityInterest,TradingSecurities,TreasurySharesNumber,TreasuryStock
symbol,,,,,,,,,,,,,,,,,,,,,
JPM,2020-12-31,12M,USD,1.402910e+11,9.050300e+10,8.839400e+10,3.416800e+10,5.276090e+11,2.487400e+10,4.105000e+09,...,2.793540e+11,1.958630e+11,3.384757e+12,5.610390e+11,3.268930e+11,2.793540e+11,3.105403e+12,3.724810e+11,1.055499e+09,8.818400e+10
JPM,2021-12-31,12M,USD,1.691720e+11,1.025700e+11,8.841500e+10,3.894300e+10,7.408340e+11,2.643800e+10,4.105000e+09,...,2.941270e+11,2.025980e+11,3.743567e+12,5.951320e+11,3.545990e+11,2.941270e+11,3.449440e+12,3.308650e+11,1.160785e+09,1.054150e+11
JPM,2022-12-31,12M,USD,1.886920e+11,1.251890e+11,8.904400e+10,3.150900e+10,5.672340e+11,2.769700e+10,4.105000e+09,...,2.923320e+11,2.040690e+11,3.665743e+12,5.881970e+11,3.398920e+11,2.923320e+11,3.373411e+12,3.601120e+11,1.170676e+09,1.073360e+11
JPM,2023-12-31,12M,USD,1.619600e+11,1.073630e+11,9.012800e+10,3.150900e+10,6.241510e+11,2.906600e+10,4.105000e+09,...,3.278780e+11,2.360930e+11,3.875393e+12,7.197030e+11,4.365370e+11,3.278780e+11,3.547515e+12,4.116130e+11,1.228275e+09,1.162170e+11

In [37]:
cashflow

,asOfDate,periodType,currencyCode,BeginningCashPosition,CashDividendsPaid,CashFlowFromContinuingFinancingActivities,CashFlowFromContinuingInvestingActivities,CashFlowFromContinuingOperatingActivities,ChangeInAccountPayable,ChangeInCashSupplementalAsReported,...,NetPreferredStockIssuance,NetShortTermDebtIssuance,OperatingCashFlow,OtherNonCashItems,PreferredStockIssuance,PreferredStockPayments,PurchaseOfInvestment,RepaymentOfDebt,RepurchaseOfCapitalStock,SaleOfInvestment
symbol,,,,,,,,,,,,,,,,,,,,,
JPM,2020-12-31,12M,USD,2.636310e+11,-1.269000e+10,5.966450e+11,-2.619120e+11,-7.991000e+10,7.415000e+09,2.639780e+11,...,3.070000e+09,4.438000e+09,-7.991000e+10,1.375000e+10,4.500000e+09,-1.430000e+09,-4.095450e+11,-1.050550e+11,-7.947000e+09,2.287930e+11
JPM,2021-12-31,12M,USD,5.276090e+11,-1.285800e+10,2.759930e+11,-1.293440e+11,7.808400e+10,4.316200e+10,2.132250e+11,...,4.775000e+09,7.773000e+09,7.808400e+10,-8.575000e+09,7.350000e+09,-2.575000e+09,-3.605410e+11,-5.493200e+10,-2.098300e+10,2.637200e+11
JPM,2022-12-31,12M,USD,7.408340e+11,-1.356200e+10,-1.262570e+11,-1.378190e+11,1.071190e+11,5.861400e+10,-1.736000e+11,...,-7.434000e+09,-8.984000e+09,1.071190e+11,2.605500e+10,0.000000e+00,-7.434000e+09,-1.599340e+11,-4.555600e+10,-1.059600e+10,1.724010e+11
JPM,2023-12-31,12M,USD,5.672340e+11,-1.346300e+10,-2.557100e+10,6.764300e+10,1.297400e+10,-2.538800e+10,5.691700e+10,...,0.000000e+00,-1.934000e+09,1.297400e+10,7.292000e+09,0.000000e+00,0.000000e+00,-1.196400e+11,-6.488000e+10,-9.824000e+09,2.152340e+11

In [38]:
income_statement

,asOfDate,periodType,currencyCode,BasicAverageShares,BasicEPS,DilutedAverageShares,DilutedEPS
symbol,,,,,,,
JPM,2020-12-31,12M,USD,3.082400e+09,8.89,3.087400e+09,8.88
JPM,2021-12-31,12M,USD,3.021500e+09,15.39,3.026600e+09,15.36
JPM,2022-12-31,12M,USD,2.965800e+09,12.10,2.970000e+09,12.09
JPM,2023-09-30,TTM,USD,2.950650e+09,16.77,2.955075e+09,16.76
JPM,2023-12-31,12M,USD,2.938600e+09,16.25,2.943100e+09,16.23
JPM,2023-12-31,TTM,USD,2.938600e+09,16.25,2.943100e+09,16.23

In [39]:
from yahooquery import Ticker

aapl = Ticker("AAPL")

aapl_info = aapl.asset_profile

for key, value in aapl_info['AAPL'].items():
    print(f"{key}: {value}")

address1: One Apple Park Way
city: Cupertino
state: CA
zip: 95014
country: United States
phone: 408 996 1010
website: https://www.apple.com
industry: Consumer Electronics
industryKey: consumer-electronics
industryDisp: Consumer Electronics
sector: Technology
sectorKey: technology
sectorDisp: Technology
longBusinessSummary: Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.
fullTimeEmployees: 150000
companyOfficers: [{'maxAge': 1, 'name': 'Mr. Timothy D. Cook', 'age': 62, 'title': 'CEO & Director', 'yearBorn': 1961, 'fiscalYear': 2023, 'totalPay': 16239562, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Luca  Maestri', 'age': 60, 'title': 'CFO & Senior VP', 'yearBorn': 1963, 'fiscalYear': 2023, 'totalPay': 4612242, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Jeffrey E. Williams', 'age': 59, 'title': 'Chief Operating Officer', 'yearBorn': 1964, 'fiscalYear': 2023, 'totalPay': 4637585, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Ms. Katherine L. Adams', 'age': 59, 'title': 'Senior VP, General Counsel & Secretary', 'yearBorn': 1964, 'fiscalYear': 2023, 'totalPay': 4618064, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': "Ms. Deirdre  O'Brien", 'age': 56, 'title': 'Senior Vice President of Retail', 'yearBorn': 1967, 'fiscalYear': 2023, 'totalPay': 4613369, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Chris  Kondo', 'title': 'Senior Director of Corporate Accounting', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. James  Wilson', 'title': 'Chief Technology Officer', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Suhasini  Chandramouli', 'title': 'Director of Investor Relations', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Greg  Joswiak', 'title': 'Senior Vice President of Worldwide Marketing', 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}, {'maxAge': 1, 'name': 'Mr. Adrian  Perica', 'age': 49, 'title': 'Head of Corporate Development', 'yearBorn': 1974, 'fiscalYear': 2023, 'exercisedValue': 0, 'unexercisedValue': 0}]
auditRisk: 4
boardRisk: 1
compensationRisk: 6
shareHolderRightsRisk: 1
overallRisk: 1
governanceEpochDate: 2024-07-30 10:00:00
compensationAsOfEpochDate: 2023-12-31 11:00:00
irWebsite: http://investor.apple.com/
maxAge: 86400

In [40]:
import yfinance as yf
import pandas as pd
from yahooquery import Ticker

# List of companies you are interested in
companies = ["IBM", "AAPL", "JPM"]

# Initialize an empty DataFrame to hold all company data
df = pd.DataFrame()

# Iterate over each company
for company in companies:
    ticker = Ticker(company)
    company_info = ticker.asset_profile
    if company in company_info:
        info = company_info[company]
        data = {
            'name': company,
            'industry': info.get('industry', 'N/A'),
            'industryKey': info.get('industryKey', 'N/A'),
            'industryDisp': info.get('industryDisp', 'N/A'),
            'sector': info.get('sector', 'N/A'),
            'sectorKey': info.get('sectorKey', 'N/A'),
            'sectorDisp': info.get('sectorDisp', 'N/A'),
            'longBusinessSummary': info.get('longBusinessSummary', 'N/A'),
            'fullTimeEmployees': info.get('fullTimeEmployees', 'N/A')
        }
        df_temp = pd.DataFrame([data])
        df = pd.concat([df, df_temp], ignore_index=True)

In [41]:
df

,name,industry,industryKey,industryDisp,sector,sectorKey,sectorDisp,longBusinessSummary,fullTimeEmployees
0,IBM,Information Technology Services,information-technology-services,Information Technology Services,Technology,technology,Technology,"International Business Machines Corporation, t...",282200
1,AAPL,Consumer Electronics,consumer-electronics,Consumer Electronics,Technology,technology,Technology,"Apple Inc. designs, manufactures, and markets ...",150000
2,JPM,Banks - Diversified,banks-diversified,Banks - Diversified,Financial Services,financial-services,Financial Services,JPMorgan Chase & Co. operates as a financial s...,313206

In [42]:
df['longBusinessSummary'][2]

'JPMorgan Chase & Co. operates as a financial services company worldwide. It operates through four segments: Consumer & Community Banking (CCB), Corporate & Investment Bank (CIB), Commercial Banking (CB), and Asset & Wealth Management (AWM). The CCB segment offers deposit, investment and lending products, cash management, and payments and services; mortgage origination and servicing activities; residential mortgages and home equity loans; and credit cards, auto loans, leases, and travel services to consumers and small businesses through bank branches, ATMs, and digital and telephone banking. The CIB segment provides investment banking products and services, including corporate strategy and structure advisory, and equity and debt market capital-raising services, as well as loan origination and syndication; payments; and cash and derivative instruments, risk management solutions, prime brokerage, and research. This segment also offers securities services, including custody, fund accounting and administration, and securities lending products for asset managers, insurance companies, and public and private investment funds. The CB segment provides financial solutions, including lending, payments, investment banking, and asset management to small and midsized companies, local governments, nonprofit clients, and large corporations, as well as investors, developers, and owners of multifamily, office, retail, industrial, and affordable housing properties. The AWM segment offers multi-asset investment management solutions in equities, fixed income, alternatives, and money market funds to institutional clients and retail investors; and retirement products and services, brokerage, custody, estate planning, lending, deposits, and investment management products to high net worth clients. JPMorgan Chase & Co. was founded in 1799 and is headquartered in New York, New York.'

In [43]:
import os
import warnings
import logging
from transformers import BertTokenizer, BertModel, logging as transformers_logging
from sklearn.neural_network import BernoulliRBM
import torch
import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  
os.environ['PYTHONWARNINGS'] = 'ignore'  

logging.getLogger('transformers').setLevel(logging.ERROR)
logging.getLogger('torch').setLevel(logging.ERROR)

transformers_logging.set_verbosity_error()

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

text = df['longBusinessSummary'][1]

inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')

with torch.no_grad():
    outputs = model(**inputs)

sentence_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()

print("size of word embeddingï¼š", sentence_embedding.shape)

rbm = BernoulliRBM(n_components=100, learning_rate=0.01, n_iter=10, random_state=42)

sentence_embedding = (sentence_embedding - sentence_embedding.min()) / (sentence_embedding.max() - sentence_embedding.min())

sentence_embedding = sentence_embedding.reshape(1, -1)

transformed_embedding = rbm.fit_transform(sentence_embedding)

print("Shape after dimension reductionï¼š", transformed_embedding.shape)
print("Vector ï¼š", transformed_embedding)

size of word embeddingï¼š (768,)
Shape after dimension reductionï¼š (1, 100)
Vector ï¼š [[2.78800107e-05 5.17582839e-06 1.63133263e-05 1.23069740e-05
  2.24590276e-05 4.56476155e-05 1.69823943e-05 2.94510173e-05
  6.55808544e-05 3.41049599e-05 1.22913152e-05 2.47535518e-05
  3.49889378e-05 3.73652983e-05 2.77613908e-05 1.88640643e-05
  4.42496603e-05 7.30344573e-06 1.33656040e-05 3.18344719e-05
  1.66940481e-05 3.63946929e-05 1.29088248e-05 2.47327862e-05
  2.59913140e-05 1.68999504e-05 2.11448423e-05 1.99441911e-05
  3.14571225e-05 4.74153458e-05 2.25306994e-05 3.24929642e-05
  2.86341401e-05 8.02502473e-06 1.55015150e-05 3.49891016e-05
  2.45198498e-05 5.34464052e-05 1.86632933e-05 1.43555772e-05
  2.15972959e-05 9.72416237e-05 1.85011831e-05 1.22451474e-05
  4.32099914e-05 8.56511833e-05 3.15313664e-05 1.81377036e-05
  3.96536379e-05 5.35719846e-05 7.59837121e-06 1.32740688e-05
  1.22744714e-05 2.71749868e-05 1.43094467e-05 1.65126730e-05
  1.77908660e-05 1.24507478e-05 2.11923234e-05 2.25825406e-05
  4.17663905e-05 3.82965081e-05 3.77403521e-05 1.36264061e-05
  1.73861081e-05 2.35618736e-05 1.57867307e-05 2.55895393e-05
  2.16902190e-05 4.44050966e-05 1.78758837e-05 1.35203018e-05
  3.03659945e-05 3.18307684e-05 4.48538049e-05 2.09688733e-05
  3.29531831e-05 2.24748619e-05 1.31610905e-05 2.18313326e-05
  1.56291135e-05 2.07975427e-05 2.02260617e-05 9.21624269e-06
  2.07421017e-05 2.18243185e-05 2.38018292e-05 6.03172703e-05
  1.59506089e-05 1.93509295e-05 2.95576283e-05 2.42915994e-05
  3.53097857e-05 2.92293607e-05 1.91573235e-05 1.27878156e-05
  2.73439073e-05 3.40758961e-05 1.59857245e-05 1.89979855e-05]]

In [44]:
import os
import warnings
import logging
from transformers import BertTokenizer, BertModel, logging as transformers_logging
from sklearn.neural_network import BernoulliRBM
import torch
import numpy as np
import pandas as pd

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  
os.environ['PYTHONWARNINGS'] = 'ignore'  

warnings.filterwarnings('ignore')

logging.getLogger('transformers').setLevel(logging.ERROR)
logging.getLogger('torch').setLevel(logging.ERROR)

transformers_logging.set_verbosity_error()

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')


def process_summary(text):
    inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding='max_length')
    with torch.no_grad():
        outputs = model(**inputs)
    sentence_embedding = outputs.last_hidden_state[:, 0, :].squeeze().numpy()
    sentence_embedding = (sentence_embedding - sentence_embedding.min()) / (sentence_embedding.max() - sentence_embedding.min())
    sentence_embedding = sentence_embedding.reshape(1, -1)
    rbm = BernoulliRBM(n_components=100, learning_rate=0.01, n_iter=10, random_state=42)
    transformed_embedding = rbm.fit_transform(sentence_embedding)
    return transformed_embedding.flatten()

embeddings = []
for i in range(len(df)):
    text = df['longBusinessSummary'][i]
    embedding = process_summary(text)
    embeddings.append(embedding)

result_df = pd.DataFrame(embeddings, columns=[f'feature_{i}' for i in range(100)])
result_df.insert(0, 'name', df['name'])

result_df

,name,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,...,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99
0,IBM,0.000033,0.000006,0.000019,0.000015,0.000026,0.000054,0.000020,0.000035,0.000079,...,0.000034,0.000028,0.000041,0.000034,0.000023,0.000016,0.000032,0.000041,0.000019,0.000022
1,AAPL,0.000028,0.000005,0.000016,0.000012,0.000022,0.000046,0.000017,0.000029,0.000066,...,0.000030,0.000024,0.000035,0.000029,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019
2,JPM,0.000018,0.000003,0.000010,0.000008,0.000014,0.000029,0.000010,0.000018,0.000043,...,0.000019,0.000015,0.000022,0.000018,0.000012,0.000008,0.000018,0.000021,0.000010,0.000012

In [45]:
merged_df = pd.merge(all_data.reset_index(), result_df, left_on='Company', right_on='name')

# Set 'Date' as index again after merging
merged_df.set_index('Date', inplace=True)
merged_df = merged_df.sort_values(by='Date', ascending=True)
merged_df.drop(columns=['name'], inplace=True)
# Display the merged and ranked DataFrame
merged_df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company,feature_0,feature_1,...,feature_90,feature_91,feature_92,feature_93,feature_94,feature_95,feature_96,feature_97,feature_98,feature_99
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02 00:00:00-05:00,103.987339,104.695998,103.810180,104.310860,3293436,0.0,0.0,IBM,0.000033,0.000006,...,0.000034,0.000028,0.000041,0.000034,0.000023,0.000016,0.000032,0.000041,0.000019,0.000022
2020-01-02 00:00:00-05:00,71.962075,73.021202,71.707013,72.960472,135480400,0.0,0.0,AAPL,0.000028,0.000005,...,0.000030,0.000024,0.000035,0.000029,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019
2020-01-02 00:00:00-05:00,121.720893,122.861575,121.259402,122.852859,10803700,0.0,0.0,JPM,0.000018,0.000003,...,0.000019,0.000015,0.000022,0.000018,0.000012,0.000008,0.000018,0.000021,0.000010,0.000012
2020-01-03 00:00:00-05:00,102.885847,103.879509,102.878145,103.478966,2482890,0.0,0.0,IBM,0.000033,0.000006,...,0.000034,0.000028,0.000041,0.000034,0.000023,0.000016,0.000032,0.000041,0.000019,0.000022
2020-01-03 00:00:00-05:00,72.183120,73.016327,72.025225,72.251137,146322800,0.0,0.0,AAPL,0.000028,0.000005,...,0.000030,0.000024,0.000035,0.000029,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-28 00:00:00-05:00,160.881662,160.881662,160.332163,160.675598,2071300,0.0,0.0,IBM,0.000033,0.000006,...,0.000034,0.000028,0.000041,0.000034,0.000023,0.000016,0.000032,0.000041,0.000019,0.000022
2023-12-28 00:00:00-05:00,193.629953,194.148591,192.662500,193.071426,34049900,0.0,0.0,AAPL,0.000028,0.000005,...,0.000030,0.000024,0.000035,0.000029,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019
2023-12-29 00:00:00-05:00,193.390581,193.889267,191.226284,192.024185,42628800,0.0,0.0,AAPL,0.000028,0.000005,...,0.000030,0.000024,0.000035,0.000029,0.000019,0.000013,0.000027,0.000034,0.000016,0.000019
2023-12-29 00:00:00-05:00,160.675597,161.097516,159.772872,160.479355,2525600,0.0,0.0,IBM,0.000033,0.000006,...,0.000034,0.000028,0.000041,0.000034,0.000023,0.000016,0.000032,0.000041,0.000019,0.000022
2023-12-29 00:00:00-05:00,167.052652,167.730692,166.689072,167.150925,6431800,0.0,0.0,JPM,0.000018,0.000003,...,0.000019,0.000015,0.000022,0.000018,0.000012,0.000008,0.000018,0.000021,0.000010,0.000012

In [46]:
all_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company
Date,,,,,,,,
2020-01-02 00:00:00-05:00,103.987339,104.695998,103.810180,104.310860,3293436,0.0,0.0,IBM
2020-01-02 00:00:00-05:00,71.962075,73.021202,71.707013,72.960472,135480400,0.0,0.0,AAPL
2020-01-02 00:00:00-05:00,121.720893,122.861575,121.259402,122.852859,10803700,0.0,0.0,JPM
2020-01-03 00:00:00-05:00,102.885847,103.879509,102.878145,103.478966,2482890,0.0,0.0,IBM
2020-01-03 00:00:00-05:00,72.183120,73.016327,72.025225,72.251137,146322800,0.0,0.0,AAPL
...,...,...,...,...,...,...,...,...
2023-12-28 00:00:00-05:00,166.413947,167.701232,166.070009,167.347473,6320100,0.0,0.0,JPM
2023-12-28 00:00:00-05:00,193.629953,194.148591,192.662500,193.071426,34049900,0.0,0.0,AAPL
2023-12-29 00:00:00-05:00,160.675597,161.097516,159.772872,160.479355,2525600,0.0,0.0,IBM
2023-12-29 00:00:00-05:00,193.390581,193.889267,191.226284,192.024185,42628800,0.0,0.0,AAPL
2023-12-29 00:00:00-05:00,167.052652,167.730692,166.689072,167.150925,6431800,0.0,0.0,JPM

In [47]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

text = (
    "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories "
    "worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose "
    "tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also "
    "provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to "
    "discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company "
    "offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, "
    "which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; "
    "Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well "
    "as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and "
    "government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through "
    "its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. "
    "was founded in 1976 and is headquartered in Cupertino, California."
)

tokens = tokenizer.tokenize(text)

num_tokens = len(tokens)

print("Number of tokens:", num_tokens)

Number of tokens: 311

In [48]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

text = (
    'JPMorgan Chase & Co. operates as a financial services company worldwide. It operates through four segments: Consumer & Community Banking (CCB), Corporate & Investment Bank (CIB), Commercial Banking (CB), and Asset & Wealth Management (AWM). The CCB segment offers deposit, investment and lending products, cash management, and payments and services; mortgage origination and servicing activities; residential mortgages and home equity loans; and credit cards, auto loans, leases, and travel services to consumers and small businesses through bank branches, ATMs, and digital and telephone banking. The CIB segment provides investment banking products and services, including corporate strategy and structure advisory, and equity and debt market capital-raising services, as well as loan origination and syndication; payments; and cash and derivative instruments, risk management solutions, prime brokerage, and research. This segment also offers securities services, including custody, fund accounting and administration, and securities lending products for asset managers, insurance companies, and public and private investment funds. The CB segment provides financial solutions, including lending, payments, investment banking, and asset management to small and midsized companies, local governments, nonprofit clients, and large corporations, as well as investors, developers, and owners of multifamily, office, retail, industrial, and affordable housing properties. The AWM segment offers multi-asset investment management solutions in equities, fixed income, alternatives, and money market funds to institutional clients and retail investors; and retirement products and services, brokerage, custody, estate planning, lending, deposits, and investment management products to high net worth clients. JPMorgan Chase & Co. was founded in 1799 and is headquartered in New York, New York.'
)

tokens = tokenizer.tokenize(text)

num_tokens = len(tokens)

print("Number of tokens:", num_tokens)

Number of tokens: 352